version: "3"
services:
  product-webapp:
    image: product-with-postgres
    networks:
      product-postgres: {}  # Correctly defined as a list
    ports:
      - "8200:8200"
    depends_on:
      - database

  database:
    image: postgres:15
    networks:
      product-postgres: {}   # Correctly defined as a list
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

networks: 
  product-postgres: {} 
