 version: "3"
 
 services: 
    product-webapp:
       image: product-with-mysql-container 
       networks:
         -product-mysql
       ports:
         -7010:7010
       depends_on:
         -database
    
    database: 
      image: mysql:8
      networks:
         -product-mysql
      environment:
        -MYSQL_ROOT_PASSWORD=password  
        -MYSQL_DATABASE=florida 
        
 networks:
   product-mysql:         
 
 